### PR TITLE
Release to staging

### PR DESCRIPTION
**Pull request by ange47rm**

### CODE REVIEW

**Review by humulla — COMMENTED** [review]
Should this patch endpoint be restricted so only certain users can update the address? I vaguely remember someone mentioning that.

**Comment by ange47rm** [comment]
> Should this patch endpoint be restricted so only certain users can update the address? I vaguely remember someone mentioning that.

Good point. Authorization has been implemented in the frontend as it's been implemented for cautionary alerts, but I think you're right, I'll try and see if I can implement the same in Asset API and then maybe re-open this PR :)

**Comment by humulla** [comment]
> > Should this patch endpoint be restricted so only certain users can update the address? I vaguely remember someone mentioning that.
> 
> Good point. Authorization has been implemented in the frontend as it's been implemented for cautionary alerts, but I think you're right, I'll try and see if I can implement the same in Asset API and then maybe re-open this PR :)

Here is an example of how you can do this: 
https://github.com/LBHackney-IT/cautionary-alerts-api/blob/master/CautionaryAlertsApi/V1/Controllers/CautionaryAlertsApiController.cs#L155

**Comment by ange47rm** [comment]
> > > Should this patch endpoint be restricted so only certain users can update the address? I vaguely remember someone mentioning that.
> > 
> > 
> > Good point. Authorization has been implemented in the frontend as it's been implemented for cautionary alerts, but I think you're right, I'll try and see if I can implement the same in Asset API and then maybe re-open this PR :)
> 
> Here is an example of how you can do this: https://github.com/LBHackney-IT/cautionary-alerts-api/blob/master/CautionaryAlertsApi/V1/Controllers/CautionaryAlertsApiController.cs#L155 and then in the serverless.yml you would have the parameter store name which is where in AWS you would define the google group name.

I was looking at exactly that, however it's not being as straightforward as I was hoping.

Cautionary Alerts API uses Hackney.Core.Authorization for this, but when I try and install this package in Asset API, it seems to "conflict" with Hackney.Core.JWT. Are you familiar with that package? I wonder if it has similar functionality to Hackney.Core.Authorization's AuthorizeEndpointByGroups

image

**Comment by ange47rm** [comment]
Cautionary Alerts API uses Hackney.Core.Authorization for this, but when I try and install this package in Asset API, it seems to conflict with Hackney.Core.JWT.

To install Hackney.Core.Authorization, I had to upgrade Hackney.Core.JWT from 1.49 to 1.72 (I think). Do you happen to know what's the difference between these two version, or better if this update of JWT could cause any issues to Asset API?

**Pull request closed without merging**
